parameters:
  name: ""
  vmImage: ""
  matrix: []

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      REPO_DIR: "scikit-learn"
      BUILD_COMMIT: "0.22.1"
      PLAT: "x86_64"
      NP_BUILD_DEP: "numpy==1.11.0"
      CYTHON_BUILD_DEP: "cython==0.29.14"
      SCIPY_BUILD_DEP: "scipy"
      JOBLIB_BUILD_DEP: "joblib==0.11"
      DAILY_COMMIT: "master"
      DAILY_BUILD: "false"
      TEST_DEPENDS: "pytest"
    strategy:
      matrix:
        ${{ insert }}: ${{ parameters.matrix }}

    steps:
      - checkout: self
        submodules: true

      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(MB_PYTHON_VERSION)
        displayName: Set python version

      - script: |
          set -e
          if [ "$BUILD_REASON" == "Schedule" ]; then
            BUILD_COMMIT=$DAILY_COMMIT
          fi
          echo "Building scikit-learn-$BUILD_COMMIT"
          echo "##vso[task.setvariable variable=BUILD_COMMIT]$BUILD_COMMIT"

          # Platform variables used in multibuild scripts
          if [ `uname` == 'Darwin' ]; then
            echo "##vso[task.setvariable variable=TRAVIS_OS_NAME]osx"
            echo "##vso[task.setvariable variable=MACOSX_DEPLOYMENT_TARGET]10.9"
          else
            echo "##vso[task.setvariable variable=TRAVIS_OS_NAME]linux"
          fi

          # Store original Python path to be able to create test_venv pointing
          # to same Python version.
          PYTHON_EXE=`which python`
          echo "##vso[task.setvariable variable=PYTHON_EXE]$PYTHON_EXE"
        displayName: Define build env variables

      - script: |
          set -e
          pip install virtualenv
          BUILD_DEPENDS="$NP_BUILD_DEP $CYTHON_BUILD_DEP $SCIPY_BUILD_DEP"

          source multibuild/common_utils.sh
          source multibuild/travis_steps.sh
          source extra_functions.sh

          # Setup build dependencies
          before_install

          # OpenMP is not present on macOS by default
          setup_compiler
          clean_code $REPO_DIR $BUILD_COMMIT
          build_wheel $REPO_DIR $PLAT
          teardown_compiler
        displayName: Build wheel
        condition: or(ne(variables['Build.Reason'], 'Schedule'), ne(variables['Daily.Build'], 'false'))

      - script: |
          set -e
          source multibuild/common_utils.sh
          source multibuild/travis_steps.sh
          source extra_functions.sh
          setup_test_venv
          install_run $PLAT
          teardown_test_venv
        displayName: Install wheel and test
        condition: or(ne(variables['Build.Reason'], 'Schedule'), ne(variables['Daily.Build'], 'false'))

      - script: pip install twine wheel keyring artifacts-keyring
        displayName: Install twine and wheel
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

      - task: TwineAuthenticate@1
        inputs:
          artifactFeed: sklearn-wheels-testing/sklearn-release
        displayName: Authenticate twine with artifact feed
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

      - script: |
          # If wheel was already uploaded then the twine command will error
          twine upload -r sklearn-release --config-file $PYPIRC_PATH \
          wheelhouse/* || exit 0
        displayName: Upload to sklearn-release azure artifact feed
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
