parameters:
  name: ""
  vmImage: ""
  matrix: []

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      REPO_DIR: "scikit-learn"
      BUILD_COMMIT: "0.22.1"
      PLAT: "x86_64"
      NP_BUILD_DEP: "numpy==1.11.0"
      CYTHON_BUILD_DEP: "cython==0.29.14"
      SCIPY_BUILD_DEP: "scipy"
      JOBLIB_BUILD_DEP: "joblib==0.11"
      DAILY_COMMIT: "master"
      DAILY_BUILD: "false"
    strategy:
      matrix:
        ${{ insert }}: ${{ parameters.matrix }}

    steps:
      - checkout: self
        submodules: true
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(MB_PYTHON_VERSION)
        displayName: Set python version
      - script: |
          set -e

          if [ "$BUILD_REASON" == "Schedule" ]; then
            if [ "$DAILY_BUILD" != "true" ]; then
              exit 0
            fi
            BUILD_COMMIT=$DAILY_COMMIT
          fi
          echo "Building scikit-learn-$BUILD_COMMIT"

          pip install virtualenv
          BUILD_DEPENDS="$NP_BUILD_DEP $CYTHON_BUILD_DEP $SCIPY_BUILD_DEP"
          TEST_DEPENDS="pytest"

          if [ `uname` == 'Darwin' ]; then
            TRAVIS_OS_NAME='osx'
            export MACOSX_DEPLOYMENT_TARGET=10.9
          else
            TRAVIS_OS_NAME='linux'
          fi

          source multibuild/common_utils.sh
          source multibuild/travis_steps.sh
          source extra_functions.sh
          before_install
        displayName: Install build environment

      - script: |
          set -e
          # OpenMP is not present on osx by default
          setup_compiler
          clean_code $REPO_DIR $BUILD_COMMIT
          build_wheel $REPO_DIR $PLAT
          teardown_compiler
        displayName: Build wheel

      - script: |
          set -e
          setup_test_venv
          install_run $PLAT
          teardown_test_venv
        displayName: Install wheel and test

      - script: pip install twine wheel keyring artifacts-keyring
        displayName: Install twine and wheel
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

      - task: TwineAuthenticate@1
        inputs:
          artifactFeed: sklearn-wheels-testing/sklearn-release
        displayName: Authenticate twine with artifact feed
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

      - script: |
          # If wheel was already uploaded then the twine command will error
          twine upload -r sklearn-release --config-file $PYPIRC_PATH \
          wheelhouse/* || exit 0
        displayName: Upload to sklearn-release azure artifact feed
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
