parameters:
  name: ""
  vmImage: ""
  matrix: []

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      BUILD_COMMIT: "0.22.1"
      SKLEARN_SKIP_NETWORK_TESTS: "1"
      NP_BUILD_DEP: "1.11.0"
      CYTHON_BUILD_DEP: "0.29.14"
      SCIPY_BUILD_DEP: "1.1.0"
      DAILY_COMMIT: "master"
      DAILY_BUILD: "false"
      PYTHON_ARCH: "x64"
    strategy:
      matrix:
        ${{ insert }}: ${{ parameters.matrix }}
    steps:
      - checkout: self
        submodules: true
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PYTHON_VERSION)
          architecture: $(PYTHON_ARCH)
        displayName: Set python version
      - bash: |
          echo PYTHON $PYTHON_VERSION $PYTHON_ARCH
          echo Build Reason $BUILD_REASON
          python --version
          python -c "import struct; print(struct.calcsize('P') * 8)"
          pip --version
        displayName: Check that we have the expected version and architecture for Python
      - bash: |
          set -xe

          if [ "$BUILD_REASON" == "Schedule" ]; then
            BUILD_COMMIT=$DAILY_COMMIT
          fi
          echo "Building scikit-learn-$BUILD_COMMIT"
          echo "##vso[task.setvariable variable=BUILD_COMMIT]$BUILD_COMMIT"

          cd scikit-learn
          git checkout $BUILD_COMMIT
          git clean -fxd
          git reset --hard
        displayName: Checkout commit
        condition: or(ne(variables['Build.Reason'], 'Schedule'), ne(variables['Daily.Build'], 'false'))

      - bash: |
          set -xe

          pip install --timeout=60 numpy==$NP_BUILD_DEP
          pip install --timeout=60 pytest wheel joblib scipy==$SCIPY_BUILD_DEP Cython==$CYTHON_BUILD_DEP
          pip install twine

          pushd scikit-learn
          python setup.py build
          python ../appveyor/vendor_vcomp140.py
          python setup.py bdist_wheel
          ls dist
          twine check dist/*
          popd
        displayName: Build wheel
        condition: or(ne(variables['Build.Reason'], 'Schedule'), ne(variables['Daily.Build'], 'false'))

      - bash: |
          set -xe
          source extra_functions.sh
          setup_test_venv
          pip install scikit-learn/dist/scikit_learn-*.whl
          mkdir tmp
          pushd tmp
          pytest -rs --pyargs sklearn
          popd
          teardown_test_venv
        displayName: Install wheel and test
        condition: or(ne(variables['Build.Reason'], 'Schedule'), ne(variables['Daily.Build'], 'false'))

      - bash: |
          pip install wheel keyring artifacts-keyring
        displayName: Install wheel keyring and artifacts-keyring
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

      - task: TwineAuthenticate@1
        inputs:
          artifactFeed: sklearn-wheels-testing/sklearn-release
        displayName: Authenticate twine with artifact feed
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

      - bash: |
          # If wheel was already uploaded then the twine command will error
          twine upload -r sklearn-release --config-file $PYPIRC_PATH scikit-learn/dist/* || exit 0
        displayName: Upload to sklearn-release azure artifact feed
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
