parameters:
  name: ""
  vmImage: ""
  matrix: []

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      BUILD_COMMIT: "0.22.1"
      SKLEARN_SKIP_NETWORK_TESTS: "1"
      NP_BUILD_DEP: "1.11.0"
      CYTHON_BUILD_DEP: "0.29.15"
      SCIPY_BUILD_DEP: "1.1.0"
      DAILY_COMMIT: "master"
      DAILY_BUILD: "false"
      PYTHON_ARCH: "x64"
    strategy:
      matrix:
        ${{ insert }}: ${{ parameters.matrix }}
    steps:
      - checkout: self
        submodules: true
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PYTHON_VERSION)
          architecture: $(PYTHON_ARCH)
        displayName: Set python version
      - script: |
          echo PYTHON %PYTHON_VERSION% %PYTHON_ARCH%
          echo Build Reason %BUILD_REASON%
          python --version
          python -c "import struct; print(struct.calcsize('P') * 8)"
          pip --version
        displayName: Check that we have the expected version and architecture for Python
      - script: |
          @echo on

          if "%BUILD_REASON%" == "Schedule" (
            if NOT "%DAILY_BUILD%" == "true" (
              exit 0
            )
            set BUILD_COMMIT=%DAILY_COMMIT%
          )
          cd scikit-learn
          git checkout %BUILD_COMMIT%
          git clean -fxd
          git reset --hard
        displayName: Checkout commit
      - script: |
          @echo on

          if "%BUILD_REASON%" == "Schedule" (
            if NOT "%DAILY_BUILD%" == "true" (
              exit 0
            )
          )

          pip install --timeout=60 numpy==%NP_BUILD_DEP%
          pip install --timeout=60 pytest wheel joblib scipy==%SCIPY_BUILD_DEP% Cython==%CYTHON_BUILD_DEP%

          pushd scikit-learn
          python setup.py bdist_wheel || exit 1
          pip install --pre --no-index --find-links dist/ scikit-learn
          popd

          mkdir tmp
          cd tmp

          REM pip install -U --timeout=60 numpy
          REM pytest -rs --pyargs sklearn
        displayName: Build, install, and test
