# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows
# https://ci.appveyor.com/project/sklearn-ci/scikit-learn

environment:
  global:
    BUILD_COMMIT: distributor-init-first
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script interpreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C ..\\appveyor\\run_with_env.cmd"
    WHEELHOUSE_UPLOADER_USERNAME: sklearn-appveyor
    WHEELHOUSE_UPLOADER_SECRET:
      secure: P1/NpWGueg+26XlcS0P6kIKO1KbRw67S6ltwEjxb+vgf0F+zfNT6FRaMPKfHSXiR

    # Make sure we don't download large datasets when running the test on
    # continuous integration platform
    SKLEARN_SKIP_NETWORK_TESTS: 1
    APPVEYOR_SKIP_FINALIZE_ON_EXIT: true
    # Minimum numpy version
    NP_BUILD_DEP: "1.11.0"
    DAILY_COMMIT: master
    DAILY_BUILD: "false"

  matrix:
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.0"
      PYTHON_ARCH: "32"
      NP_BUILD_DEP: "1.12.1"
      DAILY_BUILD: "true"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.0"
      PYTHON_ARCH: "64"
      NP_BUILD_DEP: "1.12.1"
      DAILY_BUILD: "true"

    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7.0"
      PYTHON_ARCH: "32"
      NP_BUILD_DEP: "1.14.5"
      DAILY_BUILD: "true"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.0"
      PYTHON_ARCH: "64"
      NP_BUILD_DEP: "1.14.5"
      DAILY_BUILD: "true"

    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: "3.8.0"
      PYTHON_ARCH: "32"
      NP_BUILD_DEP: "1.17.4"
      DAILY_BUILD: "true"

    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.0"
      PYTHON_ARCH: "64"
      NP_BUILD_DEP: "1.17.4"
      DAILY_BUILD: "true"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - "ECHO \"%APPVEYOR_SCHEDULED_BUILD%\""
  - ps: >-
      if ($env:APPVEYOR_SCHEDULED_BUILD -eq "True") {
        $env:CONTAINER = "sklearn-nightly"
        if ($env:DAILY_COMMIT) { $env:BUILD_COMMIT = $env:DAILY_COMMIT }
        if ($env:DAILY_BUILD -eq "false") { Exit-AppveyorBuild }
      } else {
        $env:CONTAINER = "wheels"
        $env:UPLOAD_ARGS = "--no-update-index"
      }

install:
  # Install Python (from the official .msi of http://python.org) and pip when
  # not already installed.
  - "powershell ./appveyor/install.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install -U pip"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "pip --version"

  # Checkout the request scikit-learn version in the submodule
  - "git submodule update --init --recursive"
  - "cd scikit-learn"
  - "git checkout %BUILD_COMMIT%"
  - "git clean -fxd"
  - "git reset --hard"

  # Install the build and runtime dependencies of the project.
  - "%CMD_IN_ENV% pip install --timeout=60 numpy==%NP_BUILD_DEP%"
  - "%CMD_IN_ENV% pip install --timeout=60 -r ../appveyor/requirements.txt"
  - "%CMD_IN_ENV% python setup.py build"
  - "%CMD_IN_ENV% python ../appveyor/vendor_vcomp140.py"
  - "%CMD_IN_ENV% python setup.py bdist_wheel"
  - ps: "ls dist"
  - "%CMD_IN_ENV% twine check dist/*"

  # Install the generated wheel package to test it
  - "pip install --pre --no-index --find-links dist/ scikit-learn"

# Not a .NET project, we build scikit-learn in the install step instead
build: false

test_script:
  # Remove the source dir to make sure we run the tests on the
  # installed library.
  - "rd /s /q \"sklearn\""
  # remove setup.cfg so as to not force --doctest-modules
  - "del setup.cfg"
  # Install the newest version of numpy for the tests: the goal is to ensure
  # that the scikit-learn wheels are binary compatible both with the old numpy
  # version against which they were built and the newest numpy version at the
  # time of the release, that is the version of numpy that users are most
  # likely to use.
  - "%CMD_IN_ENV% pip install -U --timeout=60 numpy"
  - "%CMD_IN_ENV% pytest -rs --pyargs sklearn"

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: 'scikit-learn\dist\*'

on_success:
  # Upload the generated wheel package to Rackspace
  # On Windows, Apache Libcloud cannot find a standard CA cert bundle so we
  # disable the ssl checks.
  - python -m wheelhouse_uploader upload
    --no-ssl-check
    --local-folder=dist
    %UPLOAD_ARGS%
    %CONTAINER%

cache:
  # Use the appveyor cache to avoid re-downloading large archives such
  # the MKL numpy and scipy wheels mirrored on a rackspace cloud
  # container, speed up the appveyor jobs and reduce bandwidth
  # usage on our rackspace account.
  - '%APPDATA%\pip\Cache'
