name: Publish to Pypi
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version upload to pypi'
        required: true
      pypi_repo:
        description: 'Repo to upload to (testpypi or pypi)'
        default: 'testpypi'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install -U wheelhouse_uploader pyyaml
    - name: Downloading wheels and sdist from staging
      run: |
        echo "Download ${{ github.event.inputs.version }} wheels and sdist"
        python -m wheelhouse_uploader fetch \
          --version ${{ github.event.inputs.version }} \
          --local-folder dist/ \
          scikit-learn \
          https://pypi.anaconda.org/scikit-learn-wheels-staging/simple/scikit-learn/
    - name: Check dist has the correct number of artifacts
      run: |
        python check_artifacts.py
    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@186232109eade3d22bfe1bca29ac9a1312598511
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_PASSWORD }}
        repository_url: https://test.pypi.org/legacy/
      if: ${{ github.event.inputs.pypi_repo }} == 'testpypi'
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@186232109eade3d22bfe1bca29ac9a1312598511
      with:
        user: __token__
        password: ${{ secrets.PYPI_PASSWORD }}
      if: ${{ github.event.inputs.pypi_repo }} == 'pypi'
